### ISSUE TITLE
TypeError: quote_from_bytes() expected bytes

### ISSUE THREAD

**Issue by monalisir** [saleweaver/python-amazon-sp-api#1277]
**Describe the bug**
When using ReportV2 to get a document will cause this error. not occurred every time. please fix it. Thanks.

 - OS: ALL

Traceback (most recent call last):
  File "/root/amzproject/backend/amazon/notification_handler/data_kiosk.py", line 50, in parse
    resp = apiClient.get_document(data_document_id, True, fn)
  File "/root/amzproject/backend/sp_api/base/helpers.py", line 21, in wrapper
    return function(*args, **kwargs)
  File "/root/amzproject/backend/sp_api/api/data_kiosk/data_kiosk.py", line 173, in get_document
    res = self._request(fill_query_params(kwargs.pop('path'), document_id), params=kwargs)
  File "/root/amzproject/backend/sp_api/base/helpers.py", line 10, in fill_query_params
    return query.format(*[parse.quote(arg, safe='') for arg in args])
  File "/root/amzproject/backend/sp_api/base/helpers.py", line 10, in <listcomp>
    return query.format(*[parse.quote(arg, safe='') for arg in args])
  File "/root/.pyenv/versions/3.9.10/lib/python3.9/urllib/parse.py", line 871, in quote
    return quote_from_bytes(string, safe)
  File "/root/.pyenv/versions/3.9.10/lib/python3.9/urllib/parse.py", line 896, in quote_from_bytes
    raise TypeError("quote_from_bytes() expected bytes")
TypeError: quote_from_bytes() expected bytes

**Comment by saleweaver** [comment]
Not reproducible. Please create issues following the template. Hint: Friendly language will be received better than 'fix it' requests.

**Comment by saleweaver** [comment]
Other note: You're talking about ReportsV2, but are using data_kiosk....

**Comment by monalisir** [comment]
> Other note: You're talking about ReportsV2, but are using data_kiosk....

Sorry for the misleading words. yes, It's Data_Kiosk, I will create an issue following the template.  Thanks for your reply.
