### ISSUE TITLE
aws_access_key sometime include slash-deliminater '/'

### ISSUE THREAD

**Issue by mitsu-ko** [saleweaver/python-amazon-sp-api#228]
Hi,

My old aws_access_key include slash-deliminater '/'.
So under following error message is wrong.

(base) PS C:\Users\glanb\python-project> python .\ama-api.py
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\cachetools\cache.py", line 44, in __getitem__       
KeyError: 'role'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\sp_api\base\client.py", line 75, in role
    role = role_cache['role']
  File "C:\ProgramData\Anaconda3\lib\site-packages\cachetools\ttl.py", line 83, in __getitem__
    return cache_getitem(self, key)
  File "C:\ProgramData\Anaconda3\lib\site-packages\cachetools\cache.py", line 46, in __getitem__
    return self.__missing__(key)
  File "C:\ProgramData\Anaconda3\lib\site-packages\cachetools\cache.py", line 73, in __missing__
    raise KeyError(key)
KeyError: 'role'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ".\ama-api.py", line 10, in <module>
    res = Orders().get_orders(CreatedAfter=(datetime.utcnow() - timedelta(days=7)).isoformat())
  File "C:\ProgramData\Anaconda3\lib\site-packages\sp_api\base\helpers.py", line 21, in wrapper
    return function(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\sp_api\api\orders\orders.py", line 51, in get_orders
    return self._request(kwargs.pop('path'), params={**kwargs})
  File "C:\ProgramData\Anaconda3\lib\site-packages\sp_api\base\client.py", line 103, in _request
    auth=self._sign_request())
  File "C:\ProgramData\Anaconda3\lib\site-packages\sp_api\base\client.py", line 81, in _sign_request
    role = self.role
  File "C:\ProgramData\Anaconda3\lib\site-packages\sp_api\base\client.py", line 77, in role
    role = self.set_role()
  File "C:\ProgramData\Anaconda3\lib\site-packages\sp_api\base\client.py", line 45, in set_role
    role = self.boto3_client.assume_role(
  File "C:\ProgramData\Anaconda3\lib\site-packages\botocore\client.py", line 386, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\botocore\client.py", line 705, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (IncompleteSignature) when calling the AssumeRole operation: Credential must have exactly 5 slash-delimited elements, e.g. keyid/date/region/service/term, got '**********/*************/20210822/us-east-1/sts/aws4_request' 

Regards,

**Comment by saleweaver** [comment]
Doesn't look like related to the library. Please include a complete, minimal and verifiable example and reopen the issue. Thanks.
