### ISSUE TITLE
Better guidance on where to obtain the credentials. 

### ISSUE THREAD

**Issue by callum80041** [saleweaver/python-amazon-sp-api#27]
Hi Currently struggling on where to obtain all the credential keys:

  refresh_token: ''
  lwa_app_id: ''
  lwa_client_secret: ''
  aws_secret_key: ''
  aws_access_key: ''
  role_arn: ''

Can you provide documentation/guidance on where these are obtained from.

**Comment by saleweaver** [comment]
Hi,

this is explained in Amazon's repo 

https://github.com/amzn/selling-partner-api-docs/blob/main/guides/developer-guide/SellingPartnerApiDeveloperGuide.md#registering-your-selling-partner-api-application

**Comment by callum80041** [comment]
```
from sp_api.api import Orders
from datetime import datetime, timedelta

# orders API
res = Orders().get_orders(CreatedAfter=(datetime.utcnow() - timedelta(days=7)).isoformat())

print(res.payload)  # json data
```

I keep getting this error:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/bin/pythonanywhere_runner.py", line 30, in _pa_run
    exec(code, new_variables)
  File "/home/darcal/python-amazon-sp-api/orders.py", line 5, in <module>
    res = Orders().get_orders(CreatedAfter=(datetime.utcnow() - timedelta(days=7)).isoformat())
  File "./sp_api/base/helpers.py", line 17, in wrapper
    return function(*args, **kwargs)
  File "./sp_api/api/orders/orders.py", line 61, in get_orders
    **self._request(kwargs.pop('path'), params={**kwargs}).json())
  File "./sp_api/base/client.py", line 104, in _request
    raise exception(e)
sp_api.base.exceptions.SellingApiForbiddenException: [{'message': 'Access to requested resource is denied.', 'code': 'Unauthorized', 'details': 'Access token is miss
ing in the request header.'}]
```
I have been through the Documentation 3 times and everything has the correct creditials setup - any suggestions?

**Comment by saleweaver** [comment]
#23
