### ISSUE TITLE
The request has an invalid parameter : scope

### ISSUE THREAD

**Issue by tector** [saleweaver/python-amazon-sp-api#278]
```python
from sp_api.api import Authorization
from sp_api.base import SellingApiException, Marketplaces

import logging
logging.basicConfig(level=logging.DEBUG)

res = Authorization(marketplace=Marketplaces.DE)
res.grantless_scope = 'sellingpartnerapi::migration'
res.get_authorization_code()
```

this code is producing this error:
`sp_api.auth.exceptions.AuthorizationError: ('invalid_scope', 'The request has an invalid parameter : scope', 400)`

Why? And how can i fix that?

**Comment by tector** [comment]
here is the full debug output:

```bash
DEBUG:botocore.hooks:Changing event name from creating-client-class.iot-data to creating-client-class.iot-data-plane
DEBUG:botocore.hooks:Changing event name from before-call.apigateway to before-call.api-gateway
DEBUG:botocore.hooks:Changing event name from request-created.machinelearning.Predict to request-created.machine-learning.Predict
DEBUG:botocore.hooks:Changing event name from before-parameter-build.autoscaling.CreateLaunchConfiguration to before-parameter-build.auto-scaling.CreateLaunchConfiguration
DEBUG:botocore.hooks:Changing event name from before-parameter-build.route53 to before-parameter-build.route-53
DEBUG:botocore.hooks:Changing event name from request-created.cloudsearchdomain.Search to request-created.cloudsearch-domain.Search
DEBUG:botocore.hooks:Changing event name from docs.*.autoscaling.CreateLaunchConfiguration.complete-section to docs.*.auto-scaling.CreateLaunchConfiguration.complete-section
DEBUG:botocore.hooks:Changing event name from before-parameter-build.logs.CreateExportTask to before-parameter-build.cloudwatch-logs.CreateExportTask
DEBUG:botocore.hooks:Changing event name from docs.*.logs.CreateExportTask.complete-section to docs.*.cloudwatch-logs.CreateExportTask.complete-section
DEBUG:botocore.hooks:Changing event name from before-parameter-build.cloudsearchdomain.Search to before-parameter-build.cloudsearch-domain.Search
DEBUG:botocore.hooks:Changing event name from docs.*.cloudsearchdomain.Search.complete-section to docs.*.cloudsearch-domain.Search.complete-section
DEBUG:botocore.loaders:Loading JSON file: [REDACTED]/.pyenv/versions/test/lib/python3.9/site-packages/botocore/data/endpoints.json
DEBUG:botocore.hooks:Event choose-service-name: calling handler <function handle_service_name_alias at 0x7fceffd0bf70>
DEBUG:botocore.loaders:Loading JSON file: [REDACTED]/.pyenv/versions/test/lib/python3.9/site-packages/botocore/data/sts/2011-06-15/service-2.json
DEBUG:botocore.hooks:Event creating-client-class.sts: calling handler <function add_generate_presigned_url at 0x7fceffd3dca0>
DEBUG:botocore.endpoint:Setting sts timeout as (60, 60)
DEBUG:botocore.loaders:Loading JSON file: [REDACTED]/.pyenv/versions/test/lib/python3.9/site-packages/botocore/data/_retry.json
DEBUG:botocore.client:Registering retry handlers for service: sts
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.amazon.com:443
DEBUG:urllib3.connectionpool:https://api.amazon.com:443 "POST /auth/o2/token HTTP/1.1" 400 92
Traceback (most recent call last):
  File "[REDACTED]/.pyenv/versions/test/lib/python3.9/site-packages/cachetools/__init__.py", line 66, in __getitem__
    return self.__data[key]
KeyError: 'access_token_7a3f4058faad259e685bf6951cf18d27'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "[REDACTED]/.pyenv/versions/test/lib/python3.9/site-packages/sp_api/auth/access_token_client.py", line 87, in get_grantless_auth
    access_token = grantless_cache[cache_key]
  File "[REDACTED]/.pyenv/versions/test/lib/python3.9/site-packages/cachetools/__init__.py", line 373, in __getitem__
    return cache_getitem(self, key)
  File "[REDACTED]/.pyenv/versions/test/lib/python3.9/site-packages/cachetools/__init__.py", line 68, in __getitem__
    return self.__missing__(key)
  File "[REDACTED]/.pyenv/versions/test/lib/python3.9/site-packages/cachetools/__init__.py", line 95, in __missing__
    raise KeyError(key)
KeyError: 'access_token_7a3f4058faad259e685bf6951cf18d27'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "[REDACTED]/test/selling-partner-api/test.py", line 17, in <module>
    res.get_authorization_code()
  File "[REDACTED]/.pyenv/versions/test/lib/python3.9/site-packages/sp_api/base/helpers.py", line 21, in wrapper
    return function(*args, **kwargs)
  File "[REDACTED]/.pyenv/versions/test/lib/python3.9/site-packages/sp_api/api/authorization/authorization.py", line 43, in get_authorization_code
    return self._request_grantless_operation(kwargs.pop('path'),  params=kwargs)
  File "[REDACTED]/.pyenv/versions/test/lib/python3.9/site-packages/sp_api/base/client.py", line 143, in _request_grantless_operation
    'x-amz-access-token': self.grantless_auth.access_token,
  File "[REDACTED]/.pyenv/versions/test/lib/python3.9/site-packages/sp_api/base/client.py", line 80, in grantless_auth
    return self._auth.get_grantless_auth(self.grantless_scope)
  File "[REDACTED]/.pyenv/versions/test/lib/python3.9/site-packages/sp_api/auth/access_token_client.py", line 91, in get_grantless_auth
    access_token = self._request(
  File "[REDACTED]/.pyenv/versions/test/lib/python3.9/site-packages/sp_api/auth/access_token_client.py", line 37, in _request
    raise AuthorizationError(error_code, error_message, response.status_code)
sp_api.auth.exceptions.AuthorizationError: ('invalid_scope', 'The request has an invalid parameter : scope', 400)
```

**Comment by saleweaver** [comment]
The migration method isn't implemented in the package at the moment and I've never used it. 
If that's for yourself, just get a refresh token from sellercentral, users can also authorize your application via the oauth flow, the authorize method is implemented. 

You're welcome to submit a PR for the migration!

**Comment by tector** [comment]
okay sorry, i was not clear enough i think:  the line
`res.grantless_scope = 'sellingpartnerapi::migration'`
is not important. If i remove that line i get the same error.

I am very new to the topic Selling Partner API.. so i don't even know right now which would be the necessary scope...

**Comment by saleweaver** [comment]
I've just tested the endpoint and it works, the error you are getting for your code is that there are parameters missing, but the scope is setup correctly. You obviously have to remove `res.grantless_scope = 'sellingpartnerapi::migration'`.

```
 res = Authorization().get_authorization_code(mwsAuthToken='test', developerId='test', sellingPartnerId='test')
```
