### ISSUE TITLE
Client does not gracefully handle 504 Gateway Timeout errors

### ISSUE THREAD

**Issue by DavidHeiniluoma** [saleweaver/python-amazon-sp-api#295]
**Describe the bug**
Many of our requests to SP API are failing today with 504 Gateway Timeouts due to the ongoing AWS us-east-1 outage. But the report client is trying and failing to parse a json body instead of gracefully handling this and throwing a SellingApiException.

**To Reproduce**

1. Call SP API get_report endpoint
2. Instead of a valid response receive a response with status code 504 and body `<html><head><title>504 Gateway Time-out</title></head><body><center><h1>504 Gateway Time-out</h1></center></body></html>`

**Expected behavior**

An exception that extends SellingApiException such as SellingApiTemporarilyUnavailableException

**Desktop (please complete the following information):**

 - OS: Linux

**Additional context**

Traceback we're receiving:

```
Traceback (most recent call last):
  File "/code/spapi_manual_client/spapi.py", line 38, in <module>
    resp = rpt_client.get_report(reportId=report_id)
  File "/code/spapi_manual_client/venv/lib/python3.9/site-packages/sp_api/base/helpers.py", line 21, in wrapper
    return function(*args, **kwargs)
  File "/code/spapi_manual_client/venv/lib/python3.9/site-packages/sp_api/api/reports/reports_v2.py", line 163, in get_report
    return self._request(fill_query_params(kwargs.pop('path'), reportId), params=kwargs)
  File /code/spapi_manual_client/venv/lib/python3.9/site-packages/sp_api/base/client.py", line 124, in _request
    return self._check_response(res)
  File "/code/spapi_manual_client/venv/lib/python3.9/site-packages/sp_api/base/client.py", line 128, in _check_response
    js = res.json() or {}
  File "/code/spapi_manual_client/venv/lib/python3.9/site-packages/requests/models.py", line 910, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by saleweaver** [comment]
Interesting finding. Added a 504 GatewayTimeout Exception
