### ISSUE TITLE
Import fails for sp_api.api.Reports

### ISSUE THREAD

**Issue by sushmitapandit** [saleweaver/python-amazon-sp-api#712]
### Discussed in https://github.com/saleweaver/python-amazon-sp-api/discussions/709

<div type='discussions-op-text'>

<sup>Originally posted by **xiaomile** August 26, 2022</sup>
Python 3.6.8 (default, Nov 16 2020, 16:55:22)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-44)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from sp_api.api import Notifications
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/sp_api/api/__init__.py", line 4, in <module>
    from .product_fees.product_fees import ProductFees
  File "/usr/local/lib/python3.6/site-packages/sp_api/api/product_fees/product_fees.py", line 7, in <module>
    class ProductFees(Client):
  File "/usr/local/lib/python3.6/site-packages/sp_api/api/product_fees/product_fees.py", line 99, in ProductFees
    def get_product_fees_estimate(self, estimate_requests: list[dict]) -> ApiResponse:
TypeError: 'type' object is not subscriptable
![image](https://user-images.githubusercontent.com/14927720/186888961-5e215887-42ed-4180-92fd-c1312c891bb1.png)
</div>

![image](https://user-images.githubusercontent.com/34543004/187061430-5acaea8f-704e-4ee3-86ba-148e91e5bc8d.png)

**Comment by saleweaver** [comment]
Python 3.6 is not supported
